export const jobRoleGroups = [
  {
    group: "Software and Engineering",
    roles: [
      "Software Engineer",
      "Frontend Engineer",
      "Backend Engineer",
      "Full Stack Engineer",
      "Mobile App Developer",
      "Android Developer",
      "iOS Developer",
      "React Developer",
      "Angular Developer",
      "Vue Developer",
      "Node.js Developer",
      "Python Developer",
      "Java Developer",
      "C# Developer",
      "PHP Developer",
      "Ruby Developer",
      "Go Developer",
      "Rust Developer",
      "C++ Developer",
      "Game Developer",
      "Embedded Software Engineer",
      "Firmware Engineer",
      "API Engineer",
      "Integration Engineer",
      "Platform Engineer",
      "Site Reliability Engineer",
      "DevOps Engineer",
      "Cloud Engineer",
      "Infrastructure Engineer",
      "Build and Release Engineer",
      "QA Engineer",
      "Automation Test Engineer",
      "Manual QA Tester",
      "Security Engineer",
      "Application Security Engineer",
      "Blockchain Developer",
      "Machine Learning Engineer",
      "AI Engineer",
      "Data Engineer",
      "Database Developer",
      "Database Administrator",
      "Solutions Architect",
      "Enterprise Architect",
      "Technical Lead",
      "Engineering Manager",
      "VP Engineering",
      "CTO",
    ],
  },
  {
    group: "Data, Analytics, and Research",
    roles: [
      "Data Analyst",
      "Business Analyst",
      "Product Analyst",
      "Marketing Analyst",
      "Financial Analyst",
      "Operations Analyst",
      "Risk Analyst",
      "Data Scientist",
      "Research Scientist",
      "Quantitative Analyst",
      "BI Developer",
      "Analytics Engineer",
      "Data Architect",
      "Statistician",
      "Economist",
      "UX Researcher",
      "Market Research Analyst",
      "Clinical Data Analyst",
      "GIS Analyst",
      "Reporting Analyst",
      "Data Visualization Specialist",
      "Actuary",
    ],
  },
  {
    group: "Product, Design, and Content",
    roles: [
      "Product Manager",
      "Associate Product Manager",
      "Senior Product Manager",
      "Technical Product Manager",
      "Product Owner",
      "Program Manager",
      "Project Manager",
      "Scrum Master",
      "UX Designer",
      "UI Designer",
      "Product Designer",
      "Graphic Designer",
      "Brand Designer",
      "Motion Designer",
      "Web Designer",
      "Industrial Designer",
      "Interior Designer",
      "Fashion Designer",
      "Content Writer",
      "Copywriter",
      "Technical Writer",
      "Content Strategist",
      "Editor",
      "Video Editor",
      "Animator",
      "Creative Director",
      "Art Director",
    ],
  },
  {
    group: "Business, Operations, and Strategy",
    roles: [
      "Operations Manager",
      "Business Operations Manager",
      "Strategy Manager",
      "Management Consultant",
      "Operations Coordinator",
      "Executive Assistant",
      "Administrative Assistant",
      "Office Manager",
      "Chief of Staff",
      "Business Development Manager",
      "Partnerships Manager",
      "Account Manager",
      "Customer Success Manager",
      "Client Relationship Manager",
      "Procurement Manager",
      "Supply Chain Manager",
      "Logistics Manager",
      "Warehouse Manager",
      "Inventory Manager",
      "Facilities Manager",
      "General Manager",
      "Regional Manager",
      "COO",
      "CEO",
    ],
  },
  {
    group: "Sales, Marketing, and Growth",
    roles: [
      "Sales Representative",
      "Inside Sales Representative",
      "Account Executive",
      "Sales Manager",
      "Sales Director",
      "Business Development Representative",
      "Sales Development Representative",
      "Marketing Manager",
      "Digital Marketing Manager",
      "Growth Marketing Manager",
      "Performance Marketing Manager",
      "SEO Specialist",
      "SEM Specialist",
      "Social Media Manager",
      "Community Manager",
      "Email Marketing Specialist",
      "Brand Manager",
      "Product Marketing Manager",
      "Public Relations Manager",
      "Events Manager",
      "Demand Generation Manager",
      "Lifecycle Marketing Manager",
      "Merchandiser",
      "Retail Sales Associate",
      "Store Manager",
      "CMO",
    ],
  },
  {
    group: "Finance, Legal, and Compliance",
    roles: [
      "Accountant",
      "Bookkeeper",
      "Auditor",
      "Tax Consultant",
      "Finance Manager",
      "Controller",
      "Investment Banker",
      "Portfolio Manager",
      "Credit Analyst",
      "Loan Officer",
      "Insurance Underwriter",
      "Claims Adjuster",
      "Compliance Officer",
      "Legal Counsel",
      "Paralegal",
      "Lawyer",
      "Contract Manager",
      "Risk Manager",
      "Treasury Analyst",
      "Payroll Specialist",
      "CFO",
    ],
  },
  {
    group: "Human Resources and Recruiting",
    roles: [
      "HR Generalist",
      "HR Manager",
      "Recruiter",
      "Technical Recruiter",
      "Talent Acquisition Specialist",
      "People Operations Manager",
      "Learning and Development Specialist",
      "Training Manager",
      "Compensation Analyst",
      "Benefits Specialist",
      "Employee Relations Specialist",
      "HR Business Partner",
      "Diversity and Inclusion Manager",
      "CHRO",
    ],
  },
  {
    group: "Healthcare and Life Sciences",
    roles: [
      "Doctor",
      "Nurse",
      "Pharmacist",
      "Physician Assistant",
      "Dentist",
      "Physical Therapist",
      "Occupational Therapist",
      "Clinical Research Associate",
      "Medical Assistant",
      "Medical Laboratory Technician",
      "Radiologic Technologist",
      "Paramedic",
      "Healthcare Administrator",
      "Public Health Specialist",
      "Biomedical Engineer",
      "Veterinarian",
      "Dietitian",
      "Psychologist",
      "Therapist",
    ],
  },
  {
    group: "Education, Government, and Social Impact",
    roles: [
      "Teacher",
      "Professor",
      "Instructional Designer",
      "School Counselor",
      "Academic Advisor",
      "Education Coordinator",
      "Librarian",
      "Social Worker",
      "Policy Analyst",
      "Urban Planner",
      "Public Administrator",
      "Nonprofit Program Manager",
      "Fundraising Manager",
      "Grant Writer",
      "Community Organizer",
      "Civil Servant",
      "Police Officer",
      "Firefighter",
      "Military Officer",
    ],
  },
  {
    group: "Manufacturing, Trades, and Services",
    roles: [
      "Mechanical Engineer",
      "Electrical Engineer",
      "Civil Engineer",
      "Chemical Engineer",
      "Manufacturing Engineer",
      "Quality Manager",
      "Process Engineer",
      "Production Supervisor",
      "Technician",
      "Electrician",
      "Plumber",
      "Carpenter",
      "Welder",
      "Mechanic",
      "Machine Operator",
      "Construction Manager",
      "Architect",
      "Real Estate Agent",
      "Chef",
      "Restaurant Manager",
      "Hotel Manager",
      "Flight Attendant",
      "Pilot",
      "Customer Support Specialist",
      "Call Center Representative",
    ],
  },
] as const;

export const allJobRoles = jobRoleGroups.flatMap((group) => group.roles);
